import { DMMF } from '@prisma/generator-helper';
import { generateTables } from './table.js';
import { generateEnums } from './enums.js';
import { generateRelations } from './relations.js';
import { generateManyToManyTables } from './many-to-many-tables.js';
import { generateProject, ProjectOptions } from './project.js';

export const autoGeneratedComment = `//// ------------------------------------------------------
//// THIS FILE WAS AUTOMATICALLY GENERATED (DO NOT MODIFY)
//// ------------------------------------------------------`;

export function generateDBMLSchema(
  dmmf: DMMF.Document,
  allowManyToMany: boolean = true,
  mapToDbSchema: boolean = false,
  includeRelationFields: boolean = true,
  projectOptions?: ProjectOptions,
): string {
  const tables = generateTables(
    dmmf.datamodel.models,
    mapToDbSchema,
    includeRelationFields,
  );
  const manyToManyTables = allowManyToMany
    ? generateManyToManyTables(dmmf.datamodel.models, mapToDbSchema)
    : [];
  const enums = generateEnums(dmmf.datamodel.enums);
  const refs = generateRelations(dmmf.datamodel.models, mapToDbSchema);
  const project = projectOptions ? generateProject(projectOptions) : [];

  return [
    autoGeneratedComment,
    ...project,
    ...tables,
    ...manyToManyTables,
    ...enums,
    ...refs,
  ].join('\n\n');
}
